/// Flutter icons Ritual
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ritual
///      fonts:
///       - asset: fonts/Ritual.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
library;
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'Ritual';
  static const String? _kFontPkg = null;

  // Fab Icons
  static const IconData directionsRun = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulbOutline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  // Habit Icons
  static const IconData rHabit = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sHabit = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dHabit = IconData(0xf057, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tHabit = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  // Check Icon
  static const IconData checkCircle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossCircle = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData circle4 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle3 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle2 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
